### PR TITLE
Add JS linting

### PR DESCRIPTION
**Pull request by noisysocks**
Thanks for writing and open sourcing this awesome tool! I'm really into the idea of a highly opinionated toolchain for JS projects.

This PR aims to address half of https://github.com/joewalnes/crunchicorn/issues/9. It:
- Makes `crunchicorn` check for [JavaScript Standard Style](http://standardjs.com/) compliance using [rollup-plugin-eslint](https://www.npmjs.com/package/rollup-plugin-eslint), [eslint-config-standard](https://www.npmjs.com/package/eslint-config-standard) and [eslint-config-standard-react](https://www.npmjs.com/package/eslint-config-standard-react).
- Adds a `--nolint` option to disable linting.
- Fixes lint errors in the example projects.

Let me know if you have any concerns or questions!

### CODE REVIEW

**Comment by noisysocks** [comment]
Something I'd like to see that's separate to this PR is addressing the lint errors that the `crunchicorn` code itself has. Perhaps by making `crunchicorn` self-hosting? :sunglasses:

**Comment by joewalnes** [comment]
Thanks for this! Sorry about the delay, I missed the PR email. I'll look through it asap

**Comment by joewalnes** [comment]
This is awesome!

**Comment by joewalnes** [comment]
Thanks for this. Yes crunchicorn itself should confirm to standardjs rules. Self hosting is a little trickier...

**Pull request merged**
